language: node_js

node_js:
  - "8"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

script:
  - npm run lint
  - npm test

after_script:
  - npm run codecov

notifications:
  email:
  - noyobo@gmail.com


deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: noyobo/md2jsonml